### ISSUE TITLE
4flix - Apresentando erro no start do jenkins

### ISSUE THREAD

**Issue by wandersonfranca** [4linux/4528#1]
A vm 4flix está apresentando falha no start do jenkins por causa da versão do java sendo necessário a utilização da versão java-11-openjdk

**Comment by pereirasamuel** [comment]
Saudações meu caro, tudo bem?
Acabei de corrigir o problema. 

> Versão do java alterada para:
>```bash
>java-11-openjdk-devel
>```

Obrigado por informar!
